apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "karna.fullname" . }}-keyring
  labels:
    {{- include "karna.componentLabels" (dict "context" . "component" "agent") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.agent.keyring.storageClass }}
  storageClassName: {{ .Values.agent.keyring.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.agent.keyring.size }}
